name: trivia
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dartz: ^0.10.0
  dio: ^4.0.0
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_riverpod: ^0.14.0+3
  get_it: ^7.2.0
  google_fonts: ^2.1.0
  overlay_support: ^1.2.1

dev_dependencies:
  build_runner: ^1.10.0
  device_preview: ^0.7.4
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0

flutter:

  uses-material-design: true
